"""sv-elab: SystemVerilog elaborator"""

module(
    name = "sv-elab",
    version = "2026-08-30",
    bazel_compatibility = [">=7.2.1"],
)

# yosys 0.62.bcr.2 is the first release that exports :hdrs for plugins.
bazel_dep(name = "yosys", version = "0.62.bcr.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_python", version = "2.0.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "fmt", version = "12.1.0")
bazel_dep(name = "boost.regex", version = "1.90.0.bcr.1")
tomlplusplus_ext = use_extension("//:dependency_support/tomlplusplus_ext.bzl", "tomlplusplus_ext")
use_repo(tomlplusplus_ext, "tomlplusplus")
vendored_hashlib_ext = use_extension("//:dependency_support/hashlib_ext.bzl", "vendored_hashlib")
use_repo(vendored_hashlib_ext, "vendored-hashlib")
slang_revision = use_repo_rule("//:dependency_support/slang_revision.bzl", "slang_revision")
slang_revision(name = "slang_revision", path = "third_party/slang")
slang_ext = use_extension("//:dependency_support/slang_ext.bzl", "vendored_slang_extension")
use_repo(slang_ext, "vendored-slang")
