name: Bazel build
on: [push, pull_request]
jobs:
  bazel:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Check slang revision matches submodule
        run: bazel test //:slang_revision_check
      - name: Build
        run: |
          bazel build //...
      - name: Test
        run: |
          bazel test //...
